## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy as np
np. linspace(-1.3, 2.5, 64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [16]:
n = 5
arr = list(np.arange(1,4))
np.array(arr*n)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [17]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [2]:
arr = np.zeros((10,10))
arr1 = [1,0,0,0,0,0,0,0,0,1]
arr[0] =np.ones(10) - arr1
arr[9]=np.ones(10) - arr1
arr+arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [3]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [7]:
#a00 = 0, a01 = 1 a02=...

def n_n(n):
    a=[]
    for i in range(n):
        a.append(list(np.arange(i,n-1+i)))
    return np.array(a)

n_n(4)
    

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [20]:
vector1 = np.arange(1,5)
vector2 = np.arange(1,8,2)
print("вектор на вектор:", vector1.dot(vector2))
arr1 = np.floor(10*np.random.random((4,4)))
arr2 = np.floor(10*np.random.random((4,4)))
print('матрицу на вектор:', arr1.dot(vector1))
print('матрицу на матрицу:\n', arr1.dot(arr2))

вектор на вектор: 50
матрицу на вектор: [60. 31. 50. 43.]
матрицу на матрицу:
 [[116.  64. 141.  42.]
 [ 42.  24.  69.   9.]
 [111.  79.  92.  26.]
 [ 82.  72.  83.   5.]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [28]:
arr = np.arange(0,1.2,0.5)
a = np.cos(arr)
b = np.sin(arr)
np.vstack((a,b))

array([[1.        , 0.87758256, 0.54030231],
       [0.        , 0.47942554, 0.84147098]])

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [36]:
A = 4*(np.random.rand(3,5))-1
A

array([[ 1.30546756, -0.01592093,  1.58094604,  1.42705066,  0.75082296],
       [ 0.73260798,  1.82621564,  2.1618892 , -0.30458594,  1.51186731],
       [ 1.8099209 , -0.12572391, -0.71271242,  0.74921035, -0.37222559]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [47]:
print('сумма всех:',np.sum(A))
print('сумма по столбцам:',np.sum(A, axis=0))
print('сумма по строкам:',np.sum(A, axis=1))
print("по строкам:")
print('среднее значение:',np.mean(A,axis=1))
print('дисперсия:',np.var(A,axis=1))
print('стандартное отклонение:',np.std(A,axis=1))

сумма всех: 12.324829835032094
сумма по столбцам: [3.84799644 1.6845708  3.03012282 1.87167508 1.89046468]
сумма по строкам: [5.0483663  5.9279942  1.34846934]
по строкам:
среднее значение: [1.00967326 1.18559884 0.26969387]
дисперсия: [0.34137953 0.77916705 0.82715466]
стандартное отклонение: [0.58427693 0.8827044  0.90948044]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [55]:
sr = np.mean(A,axis=1)
otkl = np.std(A,axis=1)
B = np.copy(A)

B[0] = (B[0] - sr[0])/ otkl[0]
B[1] = (B[1] - sr[1])/ otkl[1]
B[2] = (B[2] - sr[2])/ otkl[2]

B


array([[ 0.50625702, -1.75532206,  0.97774318,  0.71434859, -0.44302673],
       [-0.51318523,  0.7257433 ,  1.10602186, -1.68820364,  0.36962371],
       [ 1.6935241 , -0.43477326, -1.08018408,  0.52724222, -0.70580898]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [56]:
C = np.copy(A)


array([[ 1.30546756, -0.01592093,  1.58094604,  1.42705066,  0.75082296],
       [ 0.73260798,  1.82621564,  2.1618892 , -0.30458594,  1.51186731],
       [ 1.8099209 , -0.12572391, -0.71271242,  0.74921035, -0.37222559]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [58]:
B = (A.T).dot(A)
print(B)
C = (A).dot(A.T)
print()
print()
"""В первом случае вышла матрица 5х5, 5 это количество столбцов матрицы, на которую мы умножали. Во втором случае
аналогично, 3х3, 3 это количество столбцов второй матрицы. Таким образом, размер финальной матрицы зависит от размера именно 
той матрицы, на которую мы умножаем. Так же стоит отметить, что в случае с матрицами операция умножения не коммутативна."""

[[ 5.51677368  1.08956557  2.35773794  2.99583774  1.4140822 ]
 [ 1.08956557  3.35112354  4.01251073 -0.67315322  2.79583959]
 [ 2.35773794  4.01251073  7.6811143   1.06363753  4.72079001]
 [ 2.99583774 -0.67315322  1.06363753  2.69056234  0.33209362]
 [ 1.4140822   2.79583959  4.72079001  0.33209362  2.98802978]]



array([[ 6.80409813,  5.04563622,  2.02772039],
       [ 5.04563622, 10.92405829, -1.2353964 ],
       [ 2.02772039, -1.2353964 ,  4.49944722]])

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [64]:
B1 = np.eye(5)
C1 = np.eye(3)
print('B:',np.sum(B*B1))
print('C:',np.sum(C*C1))

B: 22.227603638275287
C: 22.22760363827529


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [69]:
print('det B:',np.linalg.det(B))
print('det C:',np.linalg.det(C))
print()
print('rg B:',np.linalg.matrix_rank(B))
print('rg C:',np.linalg.matrix_rank(C))
print()
print('eig B:',np.linalg.eig(B))
print('eig C:',np.linalg.eig(C))

det B: 1.702852698850475e-30
det C: 139.3082511997193

rg B: 3
rg C: 3

eig B: (array([ 1.43152230e+01,  6.38928831e+00,  1.52309235e+00, -1.50093298e-15,
       -3.90489531e-16]), array([[ 0.35898131,  0.72081759,  0.48092335, -0.34679554, -0.12888949],
       [ 0.39722271, -0.29951034,  0.58386697,  0.59833082,  0.00742704],
       [ 0.70520055, -0.20516468, -0.43867738, -0.3047983 , -0.50193386],
       [ 0.14663739,  0.5635225 , -0.48195296,  0.65472173,  0.24257364],
       [ 0.44106258, -0.17625379, -0.05563805,  0.01305886,  0.82009314]]))
eig C: (array([14.31522298,  1.52309235,  6.38928831]), array([[-0.5596911 , -0.65190269,  0.51163342],
       [-0.82862385,  0.4318017 , -0.35627209],
       [-0.01133055,  0.62335397,  0.78185769]]))


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [33]:
np.random.seed(1032201727)
np.random.randint(9)

3