## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy as np
np. linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [16]:
n = 5
arr = list(np.arange(1,4))
np.array(arr*n)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [17]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [2]:
arr = np.zeros((10,10))
arr1 = [1,0,0,0,0,0,0,0,0,1]
arr[0] =np.ones(10) - arr1
arr[9]=np.ones(10) - arr1
arr+arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [3]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [7]:
#a00 = 0, a01 = 1 a02=...

def n_n(n):
    a=[]
    for i in range(n):
        a.append(list(np.arange(i,n-1+i)))
    return np.array(a)

n_n(4)
    

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [20]:
vector1 = np.arange(1,5)
vector2 = np.arange(1,8,2)
print("вектор на вектор:", vector1.dot(vector2))
arr1 = np.floor(10*np.random.random((4,4)))
arr2 = np.floor(10*np.random.random((4,4)))
print('матрицу на вектор:', arr1.dot(vector1))
print('матрицу на матрицу:\n', arr1.dot(arr2))

вектор на вектор: 50
матрицу на вектор: [60. 31. 50. 43.]
матрицу на матрицу:
 [[116.  64. 141.  42.]
 [ 42.  24.  69.   9.]
 [111.  79.  92.  26.]
 [ 82.  72.  83.   5.]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [28]:
arr = np.arange(0,1.2,0.5)
a = np.cos(arr)
b = np.sin(arr)
np.vstack((a,b))

array([[1.        , 0.87758256, 0.54030231],
       [0.        , 0.47942554, 0.84147098]])

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [4]:
A = 4*(np.random.rand(3,5))-1
A

array([[ 0.84850312,  0.62009243,  1.86185556, -0.79303887,  1.19872888],
       [ 0.47699648,  2.72407928,  0.04711552,  2.83349728,  0.21523304],
       [ 0.28029461,  2.21470019, -0.27434549,  2.30573396,  2.46408559]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [5]:
print('сумма всех:',np.sum(A))
print('сумма по столбцам:',np.sum(A, axis=0))
print('сумма по строкам:',np.sum(A, axis=1))
print("по строкам:")
print('среднее значение:',np.mean(A,axis=1))
print('дисперсия:',np.var(A,axis=1))
print('стандартное отклонение:',np.std(A,axis=1))

сумма всех: 17.0235315769937
сумма по столбцам: [1.6057942  5.55887191 1.63462559 4.34619237 3.87804751]
сумма по строкам: [3.73614111 6.29692161 6.99046886]
по строкам:
среднее значение: [0.74722822 1.25938432 1.39809377]
дисперсия: [0.76901795 1.55902824 1.33470467]
стандартное отклонение: [0.87693669 1.24861053 1.15529419]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [6]:
sr = np.mean(A,axis=1)
otkl = np.std(A,axis=1)
B = np.copy(A)

B[0] = (B[0] - sr[0])/ otkl[0]
B[1] = (B[1] - sr[1])/ otkl[1]
B[2] = (B[2] - sr[2])/ otkl[2]

B


array([[ 0.11548713, -0.14497716,  1.27104653, -1.75641767,  0.51486118],
       [-0.6266068 ,  1.17305992, -0.97089426,  1.26069173, -0.83625058],
       [-0.96754504,  0.7068385 , -1.44763063,  0.78563555,  0.92270162]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [9]:
C = np.copy(A)
c1 = C[:, 3]
sorted = np.argsort(C[:, 3])
temp = np.zeros((3,))
for i in range(3):
    temp[i] = c1[sorted[i]]
C[:, 3] = temp
C

array([[ 0.84850312,  0.62009243,  1.86185556, -0.79303887,  1.19872888],
       [ 0.47699648,  2.72407928,  0.04711552,  2.30573396,  0.21523304],
       [ 0.28029461,  2.21470019, -0.27434549,  2.83349728,  2.46408559]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [58]:
B = (A.T).dot(A)
print(B)
C = (A).dot(A.T)
print()
print()
"""В первом случае вышла матрица 5х5, 5 это количество столбцов матрицы, на которую мы умножали. Во втором случае
аналогично, 3х3, 3 это количество столбцов второй матрицы. Таким образом, размер финальной матрицы зависит от размера именно 
той матрицы, на которую мы умножаем. Так же стоит отметить, что в случае с матрицами операция умножения не коммутативна."""

[[ 5.51677368  1.08956557  2.35773794  2.99583774  1.4140822 ]
 [ 1.08956557  3.35112354  4.01251073 -0.67315322  2.79583959]
 [ 2.35773794  4.01251073  7.6811143   1.06363753  4.72079001]
 [ 2.99583774 -0.67315322  1.06363753  2.69056234  0.33209362]
 [ 1.4140822   2.79583959  4.72079001  0.33209362  2.98802978]]



array([[ 6.80409813,  5.04563622,  2.02772039],
       [ 5.04563622, 10.92405829, -1.2353964 ],
       [ 2.02772039, -1.2353964 ,  4.49944722]])

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [64]:
B1 = np.eye(5)
C1 = np.eye(3)
print('B:',np.sum(B*B1))
print('C:',np.sum(C*C1))

B: 22.227603638275287
C: 22.22760363827529


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [69]:
print('det B:',np.linalg.det(B))
print('det C:',np.linalg.det(C))
print()
print('rg B:',np.linalg.matrix_rank(B))
print('rg C:',np.linalg.matrix_rank(C))
print()
print('eig B:',np.linalg.eig(B))
print('eig C:',np.linalg.eig(C))

"""Смотря на значения, можно сделать вывод, что ранг итоговой матрицы не зависит от порядка умножения,
однако все остальные значения различны, поэтому, опять же, нужно помнить, что операция умножения не коммутативна,
и транспанирование матрицы сильно влияет на конечный результат. """

det B: 1.702852698850475e-30
det C: 139.3082511997193

rg B: 3
rg C: 3

eig B: (array([ 1.43152230e+01,  6.38928831e+00,  1.52309235e+00, -1.50093298e-15,
       -3.90489531e-16]), array([[ 0.35898131,  0.72081759,  0.48092335, -0.34679554, -0.12888949],
       [ 0.39722271, -0.29951034,  0.58386697,  0.59833082,  0.00742704],
       [ 0.70520055, -0.20516468, -0.43867738, -0.3047983 , -0.50193386],
       [ 0.14663739,  0.5635225 , -0.48195296,  0.65472173,  0.24257364],
       [ 0.44106258, -0.17625379, -0.05563805,  0.01305886,  0.82009314]]))
eig C: (array([14.31522298,  1.52309235,  6.38928831]), array([[-0.5596911 , -0.65190269,  0.51163342],
       [-0.82862385,  0.4318017 , -0.35627209],
       [-0.01133055,  0.62335397,  0.78185769]]))


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [34]:
np.random.seed(1032201727)
np.random.randint(9)

5

In [37]:
from math import *
def f(x):
    return (cos(log(x)))/x

def integral(f, a, b, dx):
    N = int((b-a) / dx)
    xk = np.linspace(a, b, N)  # точки
    rectan = dx*np.sum(f(xk))  #метод прямоугольников
    trapez = dx/2*(f(dx) + 2*np.sum(f(xk[1:-1])) + f(xk[-1]))  # метод трапеций
    simp = dx/3*(f(dx) + 2*np.sum(f(xk[2:-1:2])) + 4*np.sum(f(xk[1:-2:2])) + f(xk[-1]))  # метод Симпсона
    return f"{rectan}, {trapez}, {simp} с шагом {dx}"

an_solution = np.float64(sin(1))
print(f"{an_solution} - аналитическое решение функции")

for i in range(5):
    print(integral(f, 1, e, 0.1**i))


0.8414709848078965 - аналитическое решение функции


TypeError: only size-1 arrays can be converted to Python scalars

In [38]:
def f(x):
    return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)

def integral(f, a, b, dx):
    N = int((b-a) / dx) 
    xk = np.linspace(a, b, N)  # точки
    rectan = dx*np.sum(f(xk))  # метод прямоугольников
    trapezoid = dx/2*(f(dx) + 2*np.sum(f(xk[1:-1])) + f(xk[-1]))  # метод трапеций
    simp = dx/3*(f(dx) + 2*np.sum(f(xk[2:-1:2])) + 4*np.sum(f(xk[1:-2:2])) + f(xk[-1]))  # метод Симпсона
    return f"{rectan}, {trapezoid}, {simp} с шагом {dx}"

an_solution = np.float64(1.110720734539591561753970247515173)  # аналитическое решение
print(f"{an_solution}")

for i in range(6):
    print(integral(f, np.float64(3/4), 2, 0.1 * 0.1**i))


1.1107207345395915
0.8238512126812755, 0.8098258036743812, 0.7737705910624484 с шагом 0.1
1.0322244184751246, 1.0312903460191785, 1.0212859253328779 с шагом 0.010000000000000002
1.0890898327101404, 1.088627061795969, 1.072525102066485 с шагом 0.0010000000000000002
1.1040534034851663, 1.1040446838813676, 1.0989731743454727 с шагом 0.00010000000000000003
inf, 1.1086409328324405, 1.1070394070810448 с шагом 1.0000000000000003e-05
inf, 1.1100661882097627, 1.1095599697750977 с шагом 1.0000000000000004e-06


C:\Users\Юлия\AppData\Local\Temp\ipykernel_9904\4048837623.py:2: RuntimeWarning: divide by zero encountered in true_divide
  return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)
